CREATE OR REPLACE 
PACKAGE PKG_PERFIL AS 
  TYPE C_CURSOR IS REF CURSOR;

  PROCEDURE SP_BUSCARXCRITERIOS(
    P_C_CURSOR  OUT C_CURSOR,
    P_NOMBRE    IN  PERFIL.NOMBRE%TYPE
  ); 

END PKG_PERFIL;

