INSERT INTO PERFIL(ID_PERFIL,NOMBRE,ESTADO) VALUES(1,'ADMINISTRADOR',1);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,ESTADO) VALUES(2,'SUPERVISOR',1);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,ESTADO) VALUES(3,'INVITADO',1);
COMMIT;

